# Generated by Django 4.1.5 on 2023-03-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='author',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
