# Generated by Django 4.1.5 on 2023-03-07 12:10

from django.db import migrations, models
import memo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountForOneMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('line_of_business', models.CharField(blank=True, max_length=128, null=True)),
                ('starting_date', models.DateField()),
                ('policy_start', models.CharField(max_length=16)),
                ('policy_end', models.CharField(max_length=16)),
                ('tot_annual_premium', models.PositiveIntegerField()),
                ('payment_made', models.PositiveIntegerField()),
                ('payment_note', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('total_no_of_lives', models.PositiveIntegerField()),
                ('insured', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('Exam Leave', 'Exam Leave'), ('Casual Leave', 'Casual Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Annual Leave', 'Annual Leave')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_resumption_date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('relief_staff_designation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('current_manager', models.CharField(blank=True, max_length=128, null=True)),
                ('approval_list', models.JSONField(blank=True, null=True)),
                ('seen_by_gm', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollee_name', models.CharField(max_length=128)),
                ('enrollee_address', models.CharField(max_length=255)),
                ('enrollee_id', models.CharField(max_length=64)),
                ('enrollee_reg_date', models.DateField()),
                ('enrollee_birth_date', models.DateField()),
                ('company_name', models.CharField(max_length=128)),
                ('provider_name', models.CharField(max_length=128)),
                ('refund_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('illness', models.TextField()),
                ('telephone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('acct_no', models.CharField(max_length=16)),
                ('tot_amt_claimed', models.PositiveIntegerField()),
                ('acct_name', models.CharField(max_length=128)),
                ('bank_name', models.CharField(max_length=128)),
                ('document1', models.FileField(blank=True, null=True, upload_to='')),
                ('document2', models.FileField(blank=True, null=True, upload_to='')),
                ('document3', models.FileField(blank=True, null=True, upload_to='')),
                ('document4', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitionMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to=memo.models.upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SendMemoForApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
