# Generated by Django 4.1.5 on 2023-03-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmemoforapproval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendmemoforapproval',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='memo.memo'),
        ),
        migrations.AddField(
            model_name='sendmemoforapproval',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisitionmemo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memotemplate',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='memo.memo'),
        ),
        migrations.AddField(
            model_name='memo',
            name='account_for_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memo.accountforonememo'),
        ),
        migrations.AddField(
            model_name='memo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memo.leavememo'),
        ),
        migrations.AddField(
            model_name='memo',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memo.refund'),
        ),
        migrations.AddField(
            model_name='memo',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memo.requisitionmemo'),
        ),
        migrations.AddField(
            model_name='leavememo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavememo',
            name='relief_staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountforonememo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
