# Generated by Django 4.1.5 on 2023-03-27 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('line_of_business', models.CharField(blank=True, max_length=128, null=True)),
                ('starting_date', models.DateField()),
                ('policy_start', models.CharField(max_length=16)),
                ('policy_end', models.CharField(max_length=16)),
                ('tot_annual_premium', models.PositiveIntegerField()),
                ('payment_made', models.PositiveIntegerField()),
                ('payment_note', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('total_no_of_lives', models.PositiveIntegerField()),
                ('insured', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('state', django_fsm.FSMField(choices=[('Initiated', 'Initiated'), ('With Head of Sales', 'With Head of Sales'), ('With ICU', 'With ICU'), ('With GMs', 'With GMs'), ('With Underwriting', 'With Underwriting'), ('Referral', 'Referral'), ('Rejected', 'Rejected')], default='Initiated', max_length=50, protected=True)),
                ('gm_approve_time', models.DateTimeField(blank=True, null=True)),
                ('icu_approve_time', models.DateTimeField(blank=True, null=True)),
                ('head_of_sales_approve_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='memotemplate',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='account_for_one',
        ),
        migrations.AlterField(
            model_name='leavememo',
            name='leave_type',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='AccountForOneMemo',
        ),
        migrations.DeleteModel(
            name='MemoTemplate',
        ),
        migrations.AddField(
            model_name='memo',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memo.salesmemo'),
        ),
    ]
