# Generated by Django 4.1.5 on 2023-03-27 15:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_salesmemo_remove_memotemplate_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmemo',
            name='state',
            field=django_fsm.FSMField(choices=[('Initiated', 'Initiated'), ('With Head Of Sales', 'With Head Of Sales'), ('With ICU', 'With ICU'), ('With GMs', 'With GMs'), ('With Underwriting', 'With Underwriting'), ('Referral', 'Referral'), ('Rejected', 'Rejected')], default='Initiated', max_length=50, protected=True),
        ),
    ]
