# Generated by Django 4.1.5 on 2023-04-11 15:51

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_approval_payment_staffrequestmemo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='approval',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('refer', 'Refer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salesmemo',
            name='state',
            field=django_fsm.FSMField(choices=[('Initiated', 'Initiated'), ('Line Manager', 'Line Manager'), ('ICU', 'ICU'), ('GMs', 'GMs'), ('Underwriting', 'Underwriting'), ('Okay', 'Okay'), ('Referral', 'Referral'), ('Rejected', 'Rejected')], default='Initiated', max_length=50, protected=True),
        ),
    ]
